// src/lib/weatherIconMap.ts

// Weather condition icons (from OpenWeatherMap codes)
export const weatherIconMapLight: Record<string, string> = {
  '01d': '/weather-icons/light/01d.svg',
  '01n': '/weather-icons/light/01n.svg',
  '02d': '/weather-icons/light/02d.svg',
  '02n': '/weather-icons/light/02n.svg',
  '03d': '/weather-icons/light/03d.svg',
  '03n': '/weather-icons/light/03n.svg',
  '04d': '/weather-icons/light/04d.svg',
  '04n': '/weather-icons/light/04n.svg',
  '09d': '/weather-icons/light/09d.svg',
  '09n': '/weather-icons/light/09n.svg',
  '10d': '/weather-icons/light/10d.svg',
  '10n': '/weather-icons/light/10n.svg',
  '11d': '/weather-icons/light/11d.svg',
  '11n': '/weather-icons/light/11n.svg',
  '13d': '/weather-icons/light/13d.svg',
  '13n': '/weather-icons/light/13n.svg',
  '50d': '/weather-icons/light/50d.svg',
  '50n': '/weather-icons/light/50n.svg',
  default: '/weather-icons/light/default.svg',

  // System icons
  humidity: '/weather-icons/light/humidity.svg',
  'wind-speed': '/weather-icons/light/wind-speed.svg',
  visibility: '/weather-icons/light/visibility.svg',
  location: '/weather-icons/light/location.svg',
  pressure: '/weather-icons/light/pressure.svg',
  sunrise: '/weather-icons/light/sunrise.svg',
  sunset: '/weather-icons/light/sunset.svg',
  'uv-index': '/weather-icons/light/uv-index.svg',
  'cloud-cover': '/weather-icons/light/cloud-cover.svg',
  continent: '/weather-icons/light/continent.svg',
  city: '/weather-icons/light/city.svg',
};

export const weatherIconMapDark: Record<string, string> = {
  '01d': '/weather-icons/dark/01d.svg',
  '01n': '/weather-icons/dark/01n.svg',
  '02d': '/weather-icons/dark/02d.svg',
  '02n': '/weather-icons/dark/02n.svg',
  '03d': '/weather-icons/dark/03d.svg',
  '03n': '/weather-icons/dark/03n.svg',
  '04d': '/weather-icons/dark/04d.svg',
  '04n': '/weather-icons/dark/04n.svg',
  '09d': '/weather-icons/dark/09d.svg',
  '09n': '/weather-icons/dark/09n.svg',
  '10d': '/weather-icons/dark/10d.svg',
  '10n': '/weather-icons/dark/10n.svg',
  '11d': '/weather-icons/dark/11d.svg',
  '11n': '/weather-icons/dark/11n.svg',
  '13d': '/weather-icons/dark/13d.svg',
  '13n': '/weather-icons/dark/13n.svg',
  '50d': '/weather-icons/dark/50d.svg',
  '50n': '/weather-icons/dark/50n.svg',
  default: '/weather-icons/dark/default.svg',

  // System icons
  humidity: '/weather-icons/dark/humidity.svg',
  'wind-speed': '/weather-icons/dark/wind-speed.svg',
  visibility: '/weather-icons/dark/visibility.svg',
  location: '/weather-icons/dark/location.svg',
  pressure: '/weather-icons/dark/pressure.svg',
  sunrise: '/weather-icons/dark/sunrise.svg',
  sunset: '/weather-icons/dark/sunset.svg',
  'uv-index': '/weather-icons/dark/uv-index.svg',
  'cloud-cover': '/weather-icons/dark/cloud-cover.svg',
  continent: '/weather-icons/dark/continent.svg',
  city: '/weather-icons/dark/city.svg',
};
